[이분탐색] 11월5일
Altu-Bitu-7/Altu-Bitu-NamSeungHyun pull request #10
Opened 2024-11-05 05:59 UTC by sh0311

이름 : 남승현
학번 : 2176121

푼 문제 : 10815, 16401, 17266
추가제출 없음

2024-11-10 14:14 UTC, avocado8 requested changes
승현님 안녕하세요! PR에 과제 파일이 보이지 않는데 한번 확인 부탁드립니다 :0

2024-11-10 15:51 UTC, sh0311 commented
제가 이상한 경로에서 실행해서 안 올라갔었네요ㅠㅠ 지금 제대로 push했습니다!

2024-11-11 10:51 UTC, avocado8 approved these changes
제출 확인했습니다 :3 ! 감사합니다

2024-11-11 12:55 UTC, sforseohn reviewed
**[이분탐색 이론 문제 코드 리뷰 완료]**

16401

승현님 안녕하세요! 이번 주도 잘 풀어주셨네요 👍👍
다만, 코드에 대한 간단한 주석이 있으면 더 좋을 것 같아요 😎
정석적으로 구현해주셔서 코멘트 드릴 부분이 없었습니다. 💯
궁금한 점이 있다면 리뷰어를 호출해주세요!

2024-11-11 12:55 UTC, sforseohn commented on 10_이분탐색/BOJ_16401.cpp
> +}
메인함수 깔끔하고 좋습니다👍👍👍

2024-11-11 12:55 UTC, sforseohn commented on 10_이분탐색/BOJ_16401.cpp
> +    int end=*max_element(cookie.begin(), cookie.end());
가장 큰 원소 구해주신 부분 좋습니다 👍

2024-11-11 12:55 UTC, sforseohn commented on 10_이분탐색/BOJ_16401.cpp
> +}
탐색 부분, 함수화 모두 좋습니다!

2024-11-11 12:55 UTC, sforseohn commented on 10_이분탐색/BOJ_16401.cpp
> +            return true;
반복문을 끝까지 돌지 않고 조건을 만족하면 바로 빠져나가게 구현해주셨네요! 이런 로직을 잘 활용해주시면 코드의 시간을 줄이는 데 도움이 됩니다!👍

2024-11-11 15:55 UTC, merged